/**
 * Live integration check against the real Groq API (no mocks).
 *   GROQ_API_KEY=... npm run test:live -w backend
 * Exits non-zero unless every sample is produced by the LLM engine and ends as valid BPMN.
 */
import { LlmService } from '../llm/llm.service';
import { runPipeline } from '../pipeline/graph';
import { SAMPLES } from '../samples';

async function main() {
  if (!process.env.GROQ_API_KEY) throw new Error('GROQ_API_KEY is not set.');
  process.env.LLM_PROVIDER = 'groq';
  const llm = new LlmService();
  console.log(`Provider: ${llm.provider}  model: ${llm.model}  base: ${llm.baseUrl}`);
  if (!(await llm.isAvailable())) throw new Error('Groq is not reachable or the API key was rejected (models endpoint failed).');
  console.log('Groq reachable, key accepted.\n');

  let failed = 0;
  for (const s of SAMPLES) {
    const t0 = Date.now();
    try {
      const r = await runPipeline({ llm, onTrace: () => undefined }, s.text, 'llm');
      const ok = r.engine === 'llm' && r.valid;
      if (!ok) failed++;
      console.log(`${ok ? 'PASS' : 'FAIL'}  ${s.title}: engine=${r.engine} valid=${r.valid} repairs=${r.repairs} ` +
        `steps=${r.metrics.tasks} actors=${r.metrics.actors} decisions=${r.metrics.decisionPoints} findings=${r.findings.length} (${Date.now() - t0} ms)`);
      console.log(`      ${r.summary}`);
    } catch (e: any) {
      failed++;
      console.log(`FAIL  ${s.title}: ${e?.message ?? e}`);
    }
  }
  if (failed) {
    console.error(`\n${failed} sample(s) failed.`);
    process.exit(1);
  }
  console.log('\nAll samples generated by the Groq LLM engine and validated.');
}
main().catch((e) => {
  console.error(String(e?.message ?? e));
  process.exit(1);
});
