// End-to-end smoke test against a deployed FlowSmith (no mocks). Usage: node scripts/smoke.mjs https://flowsmith-ai.vercel.app
// Fails unless every sample is generated by the real LLM engine (Groq) and ends as valid BPMN.
const base = (process.argv[2] || process.env.BASE_URL || 'http://localhost:3000').replace(/\/$/, '');
const email = process.env.DEMO_EMAIL || 'demo@flowsmith.ai';
const password = process.env.DEMO_PASSWORD || 'Demo@1234';

const call = async (path, init = {}) => {
  const res = await fetch(`${base}/api${path}`, { ...init, signal: AbortSignal.timeout(90_000) });
  const text = await res.text();
  let json;
  try { json = JSON.parse(text); } catch { /* non-JSON */ }
  return { status: res.status, json, text };
};

const health = await call('/health');
console.log(`GET /api/health -> ${health.status}`);
console.log(JSON.stringify(health.json?.engine ?? health.text.slice(0, 300), null, 2));
if (health.status !== 200) process.exit(1);
if (health.json.engine?.mode !== 'llm') {
  console.error('FAIL: health reports the rules engine, so the LLM server was not reachable or the key was rejected.');
  process.exit(1);
}

const login = await call('/auth/login', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ email, password }) });
console.log(`POST /api/auth/login -> ${login.status}`);
if (!login.json?.token) { console.error('FAIL: login'); process.exit(1); }
const auth = { authorization: `Bearer ${login.json.token}` };

const samples = (await call('/samples')).json;
let failed = 0;
for (const s of samples) {
  const form = new FormData();
  form.set('description', s.text);
  form.set('engine', 'llm');
  const t0 = Date.now();
  const r = await call('/processes', { method: 'POST', headers: auth, body: form });
  let rec = r.json?.record;
  if (!rec && r.json?.id) { // queued (non-serverless) hosting: poll
    for (let i = 0; i < 60 && (!rec || !['done', 'failed'].includes(rec.status)); i++) {
      await new Promise((ok) => setTimeout(ok, 1000));
      rec = (await call(`/processes/${r.json.id}`, { headers: auth })).json;
    }
  }
  const res = rec?.result;
  const ok = rec?.status === 'done' && res?.engine === 'llm' && res?.valid === true;
  if (!ok) failed++;
  console.log(`${ok ? 'PASS' : 'FAIL'}  ${s.title}: http=${r.status} status=${rec?.status} engine=${res?.engine} valid=${res?.valid} repairs=${res?.repairs} ` +
    `steps=${res?.metrics?.tasks} actors=${res?.metrics?.actors} findings=${res?.findings?.length} (${Date.now() - t0} ms)`);
  if (res?.summary) console.log(`      ${res.summary}`);
  if (!ok && (rec?.error || r.text)) console.log(`      ${String(rec?.error ?? r.text).slice(0, 300)}`);
  const extract = rec?.trace?.find((t) => t.step === 'extract');
  if (extract?.detail) console.log(`      extractor: ${extract.detail}`);
}
if (failed) { console.error(`\n${failed} sample(s) failed.`); process.exit(1); }
console.log('\nAll samples were generated by the real Groq LLM engine and validated.');
